import {
  createMongooseAdapter,
  defineResource,
  requireAuth,
  type PermissionCheck
} from "@classytic/arc";
import { buildCrudSchemasFromModel, createRepository } from "@classytic/mongokit";

import AttemptModel, { type Attempt } from "../models/attempt.model.js";
import QuizModel from "../models/quiz.model.js";

const attemptRepository = createRepository(AttemptModel);

type ResourceHookContext = {
  data: Record<string, unknown>;
  user?: {
    _id?: unknown;
    id?: unknown;
    userId?: unknown;
  };
};

const getUserId = (user: ResourceHookContext["user"]) => {
  const id = user?._id ?? user?.id ?? user?.userId;
  return typeof id === "string" ? id : undefined;
};

const hasQuizIdFilter = (query: unknown) => {
  if (!query || typeof query !== "object") {
    return false;
  }

  const params = query as Record<string, unknown>;
  return typeof params.quizId === "string" && params.quizId.trim() !== "";
};

const requireAuthForNonLeaderboard: PermissionCheck = async (ctx) => {
  if (hasQuizIdFilter(ctx.request.query)) {
    return true;
  }

  if (ctx.user) {
    return true;
  }

  return {
    granted: false,
    reason: "Authentication required unless quizId is provided for a leaderboard."
  };
};

requireAuthForNonLeaderboard._isPublic = true;

const calculateAttemptScore = async (ctx: ResourceHookContext) => {
  const userId = getUserId(ctx.user);
  if (!userId) {
    throw new Error("Authenticated user is required to submit an attempt.");
  }

  const quizId = ctx.data.quizId;
  if (typeof quizId !== "string" || quizId.trim() === "") {
    throw new Error("quizId is required.");
  }

  const answers = ctx.data.answers;
  if (!Array.isArray(answers)) {
    throw new Error(
      "answers must be an array where each item is either null or an array of answer indexes."
    );
  }

  const quiz = await QuizModel.findById(quizId)
    .select("+questions.correctAnswers")
    .lean();

  if (!quiz) {
    throw new Error("Quiz not found.");
  }

  if (answers.length !== quiz.questions.length) {
    throw new Error("answers length must match the quiz question count.");
  }

  for (let i = 0; i < answers.length; i++) {
    const a = answers[i];

    if (a === null) {
      continue;
    }

    if (
      !Array.isArray(a) ||
      a.length < 1 ||
      a.length > 4 ||
      new Set(a).size !== a.length ||
      a.some(
        (answer) =>
          !Number.isInteger(answer) || answer < 0 || answer > 3
      )
    ) {
      throw new Error(
        `answers[${i}] is invalid. Use null for skipped or 1 to 4 unique choices from 0 to 3.`
      );
    }
  }

  const normalizeCorrectAnswers = (
    question: { correctAnswers?: unknown }
  ): number[] => {
    const correctAnswers = question.correctAnswers;

    if (Array.isArray(correctAnswers)) {
      return correctAnswers.filter((answer): answer is number =>
        Number.isInteger(answer)
      );
    }

    return [];
  };

  const setsMatch = (left: number[], right: number[]) => {
    if (left.length !== right.length) {
      return false;
    }

    const sortedLeft = [...left].sort((a, b) => a - b);
    const sortedRight = [...right].sort((a, b) => a - b);

    return sortedLeft.every((value, index) => value === sortedRight[index]);
  };

  const correctAnswers = quiz.questions.map((question) =>
    normalizeCorrectAnswers(question)
  );

  const score = quiz.questions.reduce((total, question, index) => {
    const ans = answers[index];

    if (Array.isArray(ans) && setsMatch(ans, correctAnswers[index] ?? [])) {
      return total + 1;
    }

    return total;
  }, 0);

  const total = quiz.questions.length;

  return {
    ...ctx.data,
    userId,
    completedAt: new Date(),
    score,
    total,
    correctAnswers,
    answers
  };
};

export default defineResource<Attempt>({
  name: "attempt",
  displayName: "Attempt",
  prefix: "/attempts",
  adapter: createMongooseAdapter({
    model: AttemptModel,
    repository: attemptRepository,
    schemaGenerator: buildCrudSchemasFromModel
  }),
  permissions: {
    list: requireAuthForNonLeaderboard,
    get: requireAuth(),
    create: requireAuth(),
    update: requireAuth(),
    delete: requireAuth()
  },
  schemaOptions: {
    fieldRules: {
      userId: {
        type: "string",
        systemManaged: true,
        description: "Clerk user ID that submitted the attempt."
      },
      completedAt: {
        type: "date",
        systemManaged: true,
        description: "Completion timestamp generated by the API."
      },
      score: {
        type: "number",
        systemManaged: true,
        min: 0,
        description: "Calculated score generated by the API."
      }
      ,
      total: {
        type: "number",
        systemManaged: true,
        description: "Total number of questions in the quiz."
      },
      correctAnswers: {
        type: "array",
        items: { type: "array", items: { type: "number" } },
        systemManaged: true,
        description: "Correct answer indexes for each quiz question."
      },
      answers: {
        type: "array",
        items: { type: ["array", "null"] },
        description:
          "Array of user answers; each item is null or an array of selected option indexes."
      }
    },
    filterableFields: ["quizId", "userId", "score"],
    query: {
      filterableFields: {
        quizId: { type: "string" },
        userId: { type: "string" },
        score: { type: "number" }
      }
    }
  },
  hooks: {
    beforeCreate: calculateAttemptScore
  }
});
