import {
  createMongooseAdapter,
  defineResource,
  requireAuth,
  type PermissionCheck
} from "@classytic/arc";
import { buildCrudSchemasFromModel, createRepository } from "@classytic/mongokit";

import AttemptModel, { type Attempt } from "../models/attempt.model.js";
import QuizModel from "../models/quiz.model.js";

const attemptRepository = createRepository(AttemptModel);

type ResourceHookContext = {
  data: Record<string, unknown>;
  user?: {
    _id?: unknown;
    id?: unknown;
    userId?: unknown;
  };
};

const getUserId = (user: ResourceHookContext["user"]) => {
  const id = user?._id ?? user?.id ?? user?.userId;
  return typeof id === "string" ? id : undefined;
};

const hasQuizIdFilter = (query: unknown) => {
  if (!query || typeof query !== "object") {
    return false;
  }

  const params = query as Record<string, unknown>;
  return typeof params.quizId === "string" && params.quizId.trim() !== "";
};

const requireAuthForNonLeaderboard: PermissionCheck = async (ctx) => {
  if (hasQuizIdFilter(ctx.request.query)) {
    return true;
  }

  if (ctx.user) {
    return true;
  }

  return {
    granted: false,
    reason: "Authentication required unless quizId is provided for a leaderboard."
  };
};

requireAuthForNonLeaderboard._isPublic = true;

const calculateAttemptScore = async (ctx: ResourceHookContext) => {
  const userId = getUserId(ctx.user);
  if (!userId) {
    throw new Error("Authenticated user is required to submit an attempt.");
  }

  const quizId = ctx.data.quizId;
  if (typeof quizId !== "string" || quizId.trim() === "") {
    throw new Error("quizId is required.");
  }

  const answers = ctx.data.answers;
  if (!Array.isArray(answers) || answers.some((answer) => !Number.isInteger(answer))) {
    throw new Error("answers must be an array of answer indexes.");
  }

  const quiz = await QuizModel.findById(quizId)
    .select("+questions.correctAnswer")
    .lean();

  if (!quiz) {
    throw new Error("Quiz not found.");
  }

  if (answers.length !== quiz.questions.length) {
    throw new Error("answers length must match the quiz question count.");
  }

  const score = quiz.questions.reduce((total, question, index) => {
    return total + (answers[index] === question.correctAnswer ? 1 : 0);
  }, 0);

  return {
    ...ctx.data,
    userId,
    completedAt: new Date(),
    score
  };
};

export default defineResource<Attempt>({
  name: "attempt",
  displayName: "Attempt",
  prefix: "/attempts",
  adapter: createMongooseAdapter({
    model: AttemptModel,
    repository: attemptRepository,
    schemaGenerator: buildCrudSchemasFromModel
  }),
  permissions: {
    list: requireAuthForNonLeaderboard,
    get: requireAuth(),
    create: requireAuth(),
    update: requireAuth(),
    delete: requireAuth()
  },
  schemaOptions: {
    fieldRules: {
      userId: {
        type: "string",
        systemManaged: true,
        description: "Clerk user ID that submitted the attempt."
      },
      completedAt: {
        type: "date",
        systemManaged: true,
        description: "Completion timestamp generated by the API."
      },
      score: {
        type: "number",
        systemManaged: true,
        min: 0,
        description: "Calculated score generated by the API."
      }
    },
    filterableFields: ["quizId", "userId", "score"],
    query: {
      filterableFields: {
        quizId: { type: "string" },
        userId: { type: "string" },
        score: { type: "number" }
      }
    }
  },
  hooks: {
    beforeCreate: calculateAttemptScore
  }
});
